import sqlite3


# Set up the database and tables for information

con = sqlite3.connect("server_data.db")
# table --> USERTOKEN[(EMAIL, PASSWORD), TOKEN]
con.execute("""
CREATE TABLE IF NOT EXISTS USERTOKEN (
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    TOKEN TEXT NOT NULL,
    PRIMARY KEY (EMAIL, PASSWORD)
);""")

# table --> USERDETAILS[(TOKEN), NAME, PHONENUMBER, PROFILE_PICTURE, SCORE, CODE]
con.execute("""
CREATE TABLE IF NOT EXISTS USERDETAILS (
    TOKEN TEXT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    PHONENUMBER TEXT NOT NULL,
    PROFILE_PICTURE TEXT,
    SCORE REAL NOT NULL,
    CODE TEXT NOT NULL
);""")

# table --> RESTAURANTDETAILS[(RESTAURANT_ID), NAME, PHONENUMBER, ADDRESS, IMAGE, LOGO]
con.execute("""
CREATE TABLE IF NOT EXISTS RESTAURANTDETAILS (
    RESTAURANT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME TEXT NOT NULL,
    PHONENUMBER TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    IMAGE TEXT,
    LOGO TEXT
);""")

# table --> REVIEWPOSTINGS[(RESTAURANT_ID, TOKEN), RATING, COMMENT, TIME]
con.execute("""
CREATE TABLE IF NOT EXISTS REVIEWPOSTINGS (
    RESTAURANT_ID INTEGER NOT NULL,
    TOKEN TEXT NOT NULL,
    RATING INTEGER NOT NULL,
    COMMENT TEXT,
    TIME INTEGER NOT NULL,
    PRIMARY KEY (RESTAURANT_ID, TOKEN)
);""")

# table --> REVIEWBREAKDOWN[(RESTAURANT_ID, TOKEN), FOOD_RATING, CLEANLINESS_RATING, ATMOSPHRERE_RATING, SERVICE_RATING]
con.execute("""
CREATE TABLE IF NOT EXISTS REVIEWBREAKDOWN (
    RESTAURANT_ID INTEGER NOT NULL,
    TOKEN TEXT NOT NULL,
    
    FOOD_RATING INTEGER NOT NULL,
    CLEANLINESS_RATING INTEGER NOT NULL,
    ATMOSPHRERE_RATING INTEGER NOT NULL,
    SERVICE_RATING INTEGER NOT NULL,

    PRIMARY KEY (RESTAURANT_ID, TOKEN)
);""")


# table --> VERIFY[(VERIFIER, TOKEN)]
con.execute("""
CREATE TABLE IF NOT EXISTS VERIFY (
    VERIFIER TEXT NOT NULL,
    TOKEN TEXT NOT NULL,
    PRIMARY KEY (VERIFIER, TOKEN)
);""")



#TODO: insert restaurants
#RESTAURANT_ID, NAME, PHONENUMBER, ADDRESS, IMAGE, LOGO
restaurants = [
    [1, "KFC", "+852 12345678", "1 Sassoon Road", "kfc"],
    [2, "AFC", "+852 23456789", "2 Sassoon Road", "na"],
    [3, "Dairy Queen", "+852 23456789", "2 Sassoon Road", "dairy_queen"],
    [4, "McDonalds", "+852 45678901", "4 Sassoon Road", "mcdonald"],
    [5, "Jollibee", "+852 56789012", "5 Sassoon Road", "jollibee"],
    [6, "Popeyes", "+852 67890123", "6 Sassoon Road", "popeyes"],
    [7, "Red Lobster", "+852 67890123", "6 Sassoon Road", "red_lobster"],
    [8, "Burger King", "+852 67890123", "6 Sassoon Road", "burger_king"],
    [9, "Starbucks", "+852 67890123", "6 Sassoon Road", "starbucks"],
    [10, "Wendys", "+852 67890123", "6 Sassoon Road", "wendys"],
]

for i in restaurants:
    con.execute("INSERT INTO RESTAURANTDETAILS (RESTAURANT_ID, NAME, PHONENUMBER, ADDRESS, LOGO) VALUES (?,?,?,?,?);",
    (i[0],i[1],i[2],i[3],i[4]))


con.commit()
con.close()
